version: '3.3'

services:
  nodejs:
    build:
      context: ..
      dockerfile: Dockerfile
    image: nodejs
    container_name: quiz-app-api
    restart: unless-stopped
    env_file: production.env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    ports:
      - "45761:45761"
    volumes:
      - ../:/home/node/app
      - ../node_modules:/home/node/app/node_modules

volumes:
  dbdata:
  node_modules: